List structure
MAleemH/to-do-list pull request #1
Opened 2023-01-18 16:36 UTC by MAleemH

- Set up a new project with webpack
- Created an array for dynamic data output
- Wrote a function in javaScript to iterate over the tasks array
- Gave some CSS for better outlook

2023-01-18 16:43 UTC, Ismailco reviewed
Hi @MAleemH, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no professional documentation, kindly make sure to use the README provided by Microverse

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._https://github.com/MAleemH/to-do-list/pull/1

2023-01-19 04:44 UTC, Davidosky007 requested changes
Hi @MAleemH 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
## Highlights
* No linter errors 👍 
* Proper use of Github flow 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 04:44 UTC, Davidosky007 commented on package.json
> +    "build": "webpack"
* After running the build command I get a blank screen when I open the /dist/index.html file on the browser, Kindly fix this and also add more webpack script with setup instructions on your readme file on how to run your app
![image](https://user-images.githubusercontent.com/52497246/213357163-6b47c542-48d5-4811-a8d6-2f59cef80b5e.png)
![image](https://user-images.githubusercontent.com/52497246/213357176-f444161e-0651-4c94-b1c3-cf478e59c288.png)

2023-01-19 05:00 UTC, MAleemH commented on package.json
> +    "build": "webpack"
Hi @Davidosky007!
I hope you are doing great. I have tried myself but unable to fix this. I'm unable to know that how to push my src html file to dist file. If you have some free time than please help me to figure out the solution. Thanks.

2023-01-19 07:21 UTC, levy002 reviewed
## Hello @MAleemH :wave 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: 

You have submitted a project, that doesn't run linters.

- [ ] Kindly make sure to set up linters correctly so it runs to check if there are no errors on your pull request. I recommend you take a step back and read this[ lesson](https://github.com/microverseinc/linters-config/blob/master/html-css-js) to understand it clearly and follow the guideline to set it up correctly.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-19 08:42 UTC, topeogunleye approved these changes
### Hi @MAleemH, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good summary description :heavy_check_mark:
 
## [Optional] suggestions:
* Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 08:45 UTC, merged